steps:
  - name: gcr.io/$PROJECT_ID/terraform
    entrypoint: "bash"
    args:
      - "-c"
      - "for i in $(cat .priorities); do cd $i; terraform init; terraform plan -var-file=./terraform.tfvars -no-color; terraform apply -var-file=./terraform.tfvars -no-color -auto-approve; cd .. ; done;"
    dir: environments/${_ENV}
options:
  logging: CLOUD_LOGGING_ONLY

