steps:
  - name: gcr.io/$PROJECT_ID/terraform
    args: [ "init", "-no-color"]
    dir: environments/${_ENV}/bq-datasets
  - name: gcr.io/$PROJECT_ID/terraform
    args: [ "plan", "-var-file=./terraform.tfvars", "-no-color"]
    dir: environments/${_ENV}/bq-datasets
  - name: gcr.io/$PROJECT_ID/terraform
    args: [ "init", "-no-color"]
    dir: environments/${_ENV}/iam-service-accounts
  - name: gcr.io/$PROJECT_ID/terraform
    args: [ "plan", "-var-file=./terraform.tfvars", "-no-color"]
    dir: environments/${_ENV}/iam-service-accounts
options:
  logging: CLOUD_LOGGING_ONLY