test1:
  dataset_id: test1
  friendly_name: test1
  description: "test dataset"
  location: US
  access:
    - role: "roles/bigquery.dataViewer"
      user: "verdant-victory-344817@appspot.gserviceaccount.com"
    - role: "roles/bigquery.metadataViewer"
      user: "864053391115-compute@developer.gserviceaccount.com"

test2:
  dataset_id: test2
  friendly_name: test2
  location: US
  labels:
    class: 3
    provisioned_by: terraform
  access:
    - role: "roles/bigquery.dataViewer"
      user: "tf-service-account@verdant-victory-344817.iam.gserviceaccount.com"
  tables:
    - table_id: test-table1
      labels:
        table_class: 5
      schema_file_path: ./schemas/schema.json
