---
function1:
  name: function1
  src: ../../src/app1
  entry_point: hello_world
  runtime: python3
  memmory: 128
  trigger_http: true
  description: function1
    
function2:
  name: function2
  src: ../../src/app2
  entry_point: hello_world1
  runtime: python3
  memmory: 128
  trigger_http: true
  description: function2
