---
service_account1:
  name: service-account1
  project_roles:
    - roles/bigquery.jobUser
    - roles/dataproc.worker
  iam_roles:
    roles/iam.serviceAccountTokenCreator:
      - SELF
service_account2:
  name: service-account2
  project_roles:
    - roles/bigquery.jobUser
  iam_roles:
    roles/iam.serviceAccountTokenCreator:
      - SELF
