---
function1:
  name: function1
  location: US
  src: ../../src/app1
  entrypoint: hello_world
  runtime: python3
  memmory: 128
  trigger_http: true
  description: function1
    
function2:
  name: function2
  location : US
  src: ../../src/app2
  entrypoint: hello_world1
  runtime: python3
  memmory: 128
  trigger_http: true
  description: function2
