---
topic1:
  name: topic1
  labels:
    provisioned_by: terraform
    class: 3
  message_storage_policy:
    allowed_persistence_regions:
      - us-east1
      - us-central1
  message_retention_duration: 86600s
  access:
    - role: "roles/pubsub.viewer"
      members:
        - serviceAccount:864053391115-compute@developer.gserviceaccount.com
  subscriptions:
    - name: subs1-top1
      ack_deadline_seconds: 20
      labels:
        topic: topic1
      push_config:
        push_endpoint: https://example.com/push
        attributes:
          x-goog-version: v1
      access:
        - role: roles/pubsub.subscriber
          members:
            - serviceAccount:864053391115-compute@developer.gserviceaccount.com
    - name: subs2-top1
      labels:
        topic: topic2

topic2:
  name: topic2
  labels:
    provisioned_by: terraform
    class: 3
  access:
    - role: "roles/pubsub.viewer"
      members:
        - serviceAccount:864053391115-compute@developer.gserviceaccount.com
